services:
  webserver1: 
    build: .
    image: lanserver
    ports: 
      - "8000"
    deploy:
     replicas: 3 

  # Used for testing load balancer.
  # webserver2: 
  #   build: .
  #   image: lanserver
  #   ports: 
  #     - "8000"

  # webserver3: 
  #   build: .
  #   image: lanserver
  #   ports: 
  #     - "8000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: admin  
      MONGO_INITDB_DATABASE: DB 
  
  nginx: 
    image: nginx:latest
    ports: 
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webserver1