services:
  frontend:
    build: .
    image: lanfrontend-stable:latest
    restart: always
    ports:
      - "3000:80"

  webserver1:
    build: .
    image: lanserver-stable:latest
    restart: always
    ports:
      - "8080"
    deploy:
      replicas: 2

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webserver1
