services:
  frontend:
    build: .
    image: lanfrontend-stable
    ports:
      - "3000:3000"

  webserver1:
    build: .
    image: lanserver-stable
    ports:
      - "8000"
    deploy:
      replicas: 2

  # Used for testing load balancer.
  # webserver2:
  #   build: .
  #   image: lanserver2.2
  #   ports:
  #     - "8000"

  # webserver3:
  #   build: .
  #   image: lanserver2.3
  #   ports:
  #     - "8000"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - webserver1
