name: Deploy
on:
  push:
    branches:
        - config-github-actions

jobs:
  deploy-ec2:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: List files
          run: |
            ls ~/work/LAN/LAN/Backend
          shell: bash

        - name: SSH into EC2 and deploy with Docker Compose
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY}}
            port: ${{ secrets.EC2_SSH_PORT }}
            script: | 
              ls
              cd home/ec2-user/
              pwd

        - name: Transfer Docker Compose file
          uses: appleboy/scp-action@master
          with: 
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY}}
            port: ${{ secrets.EC2_SSH_PORT }}
            source: ~/work/LAN/LAN/Backend/docker-compose.yaml
            target: "/home/ec2-user/"