name: CI/CD Pipeline
on: 
  push: 
    branches: [develop]

jobs:
  quality-check:
    name: Official SonarQube Scan
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/chechout@v3
      with:
        fetch-depth: 0

    - name: Sonar Qube Scanning
      uses: actions/sonarqube-action@v1.2.0
      with:
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
        projectKey: "LAN-project"
